---
dependencies: []

galaxy_info:
  author: alexandermeindl
  description: System watch (with Git, Redmine and Drupal support) for Debian and Ubuntu.
  company: AlphaNodes GmbH
  license: Apache License 2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
  galaxy_tags:
    - monitoring
    - redmine
    - drupal
    - etc
