---
dependencies: []

galaxy_info:
  author: alexandermeindl
  description: Run Drupal tasks (e.g. rollout, cron, scheduler)
  company: AlphaNodes GmbH
  license: Apache License 2.0
  min_ansible_version: '2.14'
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
  galaxy_tags:
    - drupal
    - deploy
    - cron
